### ISSUE TITLE
Collaboration.

### ISSUE THREAD

**Issue by whitediamondscountinguap** [sharlotte-mobile/ExampleMod#2]
Hello to Charlotte and VozDuh, i dont find any other ways to connect with you, therefore I am writing here. I am the author of the mod Braindustry and I really like your mod and its idea, I want to do some kind of collaboration with you or something like that. You can write to me in Discord -  PixaxeOfPixie #9008
Or to the Russian social network Vkontakte - https://m.vk.com/pixaxeofpixie
I'll be glad if something comes out with you!

**Comment by Sharlottes** [comment]
why do i read this now
