### ISSUE TITLE
thuis mod does not eally work

### ISSUE THREAD

**Issue by davlucas** [sharlotte-mobile/ExampleMod#5]
Some blocks works smoothly, but for some others, there are issues:
[W] testmod-activationmatter-weaver: Ignoring unknown field: outputItem (mindustry.world.Block)
[W] testmod-activationmatter-weaver: Ignoring unknown field: craftTime (mindustry.world.Block)
[W] testmod-atmospheric-cooler: Ignoring unknown field: outputLiquid (mindustry.world.Block)
[W] testmod-atmospheric-cooler: Ignoring unknown field: craftTime (mindustry.world.Block)
[W] testmod-coredvalut: Ignoring unknown field: resupplyRate (mindustry.world.Block)
[W] testmod-coredvalut: Ignoring unknown field: resupplyRange (mindustry.world.Block)
[W] testmod-coredvalut: Ignoring unknown field: ammoAmount (mindustry.world.Block)
[W] testmod-coredvalut: Ignoring unknown field: unitType (mindustry.world.Block)
[W] testmod-impact-projector: Ignoring unknown field: phaseUseTime (mindustry.world.Block)
[W] testmod-impact-projector: Ignoring unknown field: phaseShieldBoost (mindustry.world.Block)
[W] testmod-impact-projector: Ignoring unknown field: radius (mindustry.world.Block)
[W] testmod-impact-projector: Ignoring unknown field: shieldHealth (mindustry.world.Block)
[W] testmod-impact-projector: Ignoring unknown field: cooldownNormal (mindustry.world.Block)
[W] testmod-impact-projector: Ignoring unknown field: cooldownLiquid (mindustry.world.Block)
[W] testmod-impact-projector: Ignoring unknown field: cooldownBrokenBase (mindustry.world.Block)
[W] testmod-multi-cultivator: Ignoring unknown field: outputItem (mindustry.world.Block)
[W] testmod-multi-cultivator: Ignoring unknown field: craftTime (mindustry.world.Block)
[W] testmod-multi-cultivator: Ignoring unknown field: craftEffect (mindustry.world.Block)
[W] testmod-multi-projector: Ignoring unknown field: phaseUseTime (mindustry.world.Block)
[W] testmod-multi-projector: Ignoring unknown field: phaseShieldBoost (mindustry.world.Block)
[W] testmod-multi-projector: Ignoring unknown field: radius (mindustry.world.Block)
[W] testmod-multi-projector: Ignoring unknown field: shieldHealth (mindustry.world.Block)
[W] testmod-multi-projector: Ignoring unknown field: cooldownNormal (mindustry.world.Block)
[W] testmod-multi-projector: Ignoring unknown field: cooldownLiquid (mindustry.world.Block)
[W] testmod-multi-projector: Ignoring unknown field: cooldownBrokenBase (mindustry.world.Block)
[W] testmod-plast-salvo: Ignoring unknown field: range (mindustry.world.Block)
[W] testmod-power-processor: Ignoring unknown field: instructionsPerTick (mindustry.world.Block)
[W] testmod-power-processor: Ignoring unknown field: range (mindustry.world.Block)

**Comment by Sharlottes** [comment]
Might be js is broken. Check tomorrow

**Comment by ghost** [comment]
is this fixed? if so why isn't this closed?

**Comment by Sharlottes** [comment]
> is this fixed? if so why isn't this closed?

because i forgot to close.
