### ISSUE TITLE
Planet Grasia and Tantrosia keeps losing the save file 

### ISSUE THREAD

**Issue by LordDennis18** [sharlotte-mobile/ExampleMod#7]
Everytime i close the game and reopen it my save file from the desert canyon keeps corrupting or something. I also tested it in the central base and the same thing happened and also in the Tantrosia, is it still in development?

**Comment by LordDennis18** [comment]
This is the before and after in Central Base
![Screenshot_2021-02-24-22-10-10-47_13f989b68d7412e5a177fb13b36ac66f](https://user-images.githubusercontent.com/78860136/109013438-216cbb00-76ee-11eb-856e-d9f3dd5b9295.jpg)
![Screenshot_2021-02-24-22-17-19-70_13f989b68d7412e5a177fb13b36ac66f](https://user-images.githubusercontent.com/78860136/109013451-2598d880-76ee-11eb-92e6-00ad9f83cdd4.jpg)

**Comment by Sharlottes** [comment]
Unfortunately, planetary content is very unstable. If there is a crash, please tell me know so that i can disable or remove them.
planet content will be moved to Sharustry, the java mod

**Comment by LordDennis18** [comment]
> Unfortunately, planetary content is very unstable. If there is a crash, please tell me know so that i can disable or remove them.
> planet content will be moved to Sharustry, the java mod

It doesn't crash but it corrupts the save file of the sector every time i leave the game.

**Comment by Sharlottes** [comment]
solved to remove planet ohno
